apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.gitlabconfig.spec.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.gitlabconfig.spec.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabconfig.spec.capacity.storage }}
