# Default values for chartbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

namespace: gitlab

ingress:
  enabled: true
  host: "gitlab.example.com" 

  className: "nginx-default"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: 
    secretName: gitlab-tls 
    certificate: "${tls.cert | base64 }"
    key: "${tls.key | base64 }"

deployment:
  gitlab:
    imagePullSecrets: []
    imageName: gitlab/gitlab-ce
    imageTag: 15.10.8-ce.0
    imagePullPolicy: Always
    replicaCount: 1
    ingressPath: /
    service:  
      name: gitlab-ce   
      type: ClusterIP
      port: 8080    
    
  postgresql:
    imagePullSecrets: []
    imageName: postgres
    imageTag: 12.2-alpine
    imagePullPolicy: Always
    replicaCount: 1 
    service: 
      name: postgresql
      type: ClusterIP
      port: 5432

persistence:
  postgresql:
    spec:
      capacity:
        storage: 10Gi
      persistentVolumeReclaimPolicy: Recycle
      storageClassName: nfs-postgresql-gitlab
      pvcName: nfs-gitlab-postgresql-pvc
      nfs:
        path: /var/nfs/gitlab/postgresql/data
        server: 127.0.0.1
  gitlabdata:
    spec:
      capacity:
        storage: 10Gi
      persistentVolumeReclaimPolicy: Recycle
      storageClassName: nfs-gitlab-data
      pvcName: nfs-gitlab-pvc-data
      nfs:
        path: /var/nfs/gitlab/data
        server: 127.0.0.1
  gitlabconfig:
    spec:
      capacity:
        storage: 10Gi
      persistentVolumeReclaimPolicy: Recycle
      storageClassName: nfs-gitlab-config
      pvcName: nfs-gitlab-pvc-config
      nfs:
        path: /var/nfs/gitlab/config
        server: 127.0.0.1
  gitlablogs:
    spec:
      capacity:
        storage: 10Gi
      persistentVolumeReclaimPolicy: Recycle
      storageClassName: nfs-gitlab-logs
      pvcName: nfs-gitlab-pvc-logs
      nfs:
        path: /var/nfs/gitlab/logs
        server: 127.0.0.1
     
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

