apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Values.persistence.postgresql.spec.pvcName }}
  namespace: {{ .Values.namespace }} 
spec:
  storageClassName: {{ .Values.persistence.postgresql.spec.storageClassName }}
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: {{ .Values.persistence.postgresql.spec.capacity.storage }}
