apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.postgresql.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-gitlab
spec:
  selector:
    app: postgres-gitlab
  type: {{ .Values.deployment.postgresql.service.type }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.deployment.postgresql.service.port }}
      {{- if or (eq "NodePort" .Values.deployment.postgresql.service.type) (eq "ClusterIP" .Values.deployment.postgresql.service.type) }}      
      targetPort: 5432
      {{- else }}
        {{- fail "Invalid service type. Service type must be NodePort or ClusterIP" }}
      {{- end }}    



  
